### ISSUE TITLE
Error thrown in markov chain monte carlo

### ISSUE THREAD

**Issue by ff995** [arm61/uravu#25] opened 2020-09-17 16:01 UTC
Hello again, I am getting an error message saying 'probablity function returned NaN' when running mcmc for a sample size of 135. Do you know what may cause this? 

I also have some questions about how mcmc works. In your code, ln_probability is passed into EnsembleSampler in the mcmc function, is this replacing the log_prob function used in the emcee module? Also, ln_probability throws an error when I pass an array of values into it, including arrays of abscissa and ordinate values.

![image](https://user-images.githubusercontent.com/70442131/93496594-4f5fff00-f907-11ea-8117-15e6340a0189.png)
![image](https://user-images.githubusercontent.com/70442131/93496627-5ab32a80-f907-11ea-8728-cc956044ba34.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Python Version: [e.g. 3.7]
 - uravu Version: [e.g. 1.0.1]

**Comment by ff995** [comment] 2020-09-18 14:08
Actually never mind, I have realised my mistake....

**Comment by ff995** [comment] 2020-09-20 17:09
My apologies, but I have encountered a similar error whilst using distributions. MCMC works well with a sample of 135 normal distributions, but throws the error shown above when the sample size is 150.  I am sub-sampling a much larger array so the 2 samples have few elements in common.

**Comment by arm61** [comment] 2020-09-20 18:05
Hey @ff995 could you potential share more infomation about the problem? Or is it the code from the original issue?

**Comment by ff995** [comment] 2020-09-20 18:34
The function I am using now is very similar to the last but I have included a screenshot of this newer one as well as the errors and the code for the conversion of ordinate values to distributions. 

![image](https://user-images.githubusercontent.com/70442131/93718943-4c6b4580-fb77-11ea-8e7f-9b227898d177.png)
![image](https://user-images.githubusercontent.com/70442131/93718990-a10ec080-fb77-11ea-9b24-9d67ca71136b.png)
![image](https://user-images.githubusercontent.com/70442131/93718999-ad931900-fb77-11ea-9e02-ee961405de91.png)
![image](https://user-images.githubusercontent.com/70442131/93719031-df0be480-fb77-11ea-9795-26773c8d2c82.png)

**Comment by arm61** [comment] 2020-09-21 16:52
Sorry for the delay. 

What are the contents of `y` in the lowest cell? Cause it still looks like a problem with the creation of the kernel density estimation object.

**Comment by ff995** [comment] 2020-09-21 18:29
y is a 1D array of experimental intensities. I am first removing all values where the intensity is zero from y and then I am creating a list of Distribution objects with values in y as the mean.

![image](https://user-images.githubusercontent.com/70442131/93806191-b3a0fc80-fc40-11ea-8cb5-c04358296ab8.png)

**Comment by arm61** [comment] 2020-09-28 15:38
Since you are working with normal distributions, can you try passing the `y` and `ordinate_error=y*0.2` in to the `Relationship` class? This is to test if it is a problem in the creation of the `Distribution`-class object. 

Sorry about the delay again (real life getting in the way of programming fun!)

**Comment by ff995** [comment] 2020-09-29 19:45
Thanks for responding. Running 'mini' with an ordinate error and no distribution still works with a sample size of 135 but throws the same error with a larger sample size.

**Comment by arm61** [comment] 2020-09-30 08:40
Is it possible that at some extrema of the parameters (`guess1`, etc.) there is a nonreal result to the `calculate_Au3_secondary` function?

**Comment by ff995** [comment] 2020-10-02 22:35
After some probing (and asking the creator of the function), I don't think this is the case. With non-physical values the function will still return real numbers. I have also run the function with more restricted bounds but the error still persists.

**Comment by arm61** [comment] 2020-10-09 08:19
Okay. I don't think I can debug this remotely. Would you be willing to send the relevant notebooks to me over email? (my email address should be on my profile)

**Comment by ff995** [comment] 2020-10-12 22:46
Hi Andrew, attached is the notebook I have been using.

[UravuProject (1).zip](https://github.com/arm61/uravu/files/5367975/UravuProject.1.zip)

**Comment by arm61** [comment] 2020-10-14 10:11
Hey! There are a few functions `normalise`, `convert_to_wavelength`, etc that are called in this notebook but that aren't defined in the notebook, furthermore, the `'sec_trace.txt'` is necessary to ensure everything works correctly. Would you possibly be able to send those over also? To accurately diagnose the problems, I need to be able to run everything 😄

**Comment by arm61** [comment] 2020-10-14 10:13
These functions might be in the `MMM_core.ipynb` notebook?

**Comment by ff995** [comment] 2020-10-14 14:03
Hi, I'm very sorry, here is a file containing the other notebooks.
[UravuProject (1).zip](https://github.com/arm61/uravu/files/5378667/UravuProject.1.zip)

**Comment by arm61** [comment] 2020-10-15 08:24
There is still no data file (`'sec_trace.txt'`) that I can find...

**Comment by ff995** [comment] 2020-10-16 15:57
Very sorry (again), here is the document you're looking for.
[sec_trace (1).txt](https://github.com/arm61/uravu/files/5392801/sec_trace.1.txt)

**Comment by arm61** [comment] 2020-10-20 14:23
Hey! So the good news is I know what the problem is, the bad news is there is no nice fix yet. I am gonna work a fix over the next few weeks. 

In the meantime if you select less than 100 points from the trace I have been able to get something that works. This is due to the numerical instability in the `kde` object that is used internally within `uravu`.

**Comment by arm61** [comment] 2020-10-21 15:22
Just to keep you up to date. So the problem was something deeper in the `scipy` library. However, I spent today working on a more robust solution and have made a [pull request](https://github.com/scipy/scipy/pull/12989) to the scipy package with my fix. 

I am not sure how long this will take to make its way into the main scipy implementation. So I will put a workaround into `uravu` in the meantime and let you know when it is ready. Then once scipy have merged my change, I will silently update `uravu`.

**Comment by arm61** [comment] 2020-10-21 17:11
That is the newest version of `uravu` up on PyPI, so if you run `pip install -U uravu` this should install `1.2.0` which includes the workaround until `scipy` merge my change. 

I will close this issue for now, but if my workaround doesn't solve things please reopen.

**Closed by arm61** 2020-10-21 17:11 UTC
